name: Cross-Platform CMake CI

on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

jobs:
  cross_build:
    name: cross_build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI script (Linux / macOS)
        if: matrix.os != 'windows-latest'
        run: |
          chmod +x ci.sh
          ./ci.sh
        shell: bash

      - name: Upload build artifacts (Linux/macOS)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ github.run_id }}
          path: build

      - name: Run CI script (Windows)
        if: matrix.os == 'windows-latest'
        run: .\ci.bat
        shell: cmd

      - name: Upload build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-${{ github.run_id }}
          path: build

      - name: Deploy
        run: echo "Deploy step (placeholder) - implement deployment here"

